---

- name: warning
  debug:
    msg: 'EPEL is for RedHat-like operating systems.'


# The proxy server - proxy server:port number
- name: use a proxy for yum
  when: https_proxy_url is defined and ansible_os_family == 'RedHat'
  lineinfile:
    dest: /etc/yum.conf
    state: present
    regexp: '^proxy'
    line: "proxy=https://{{  https_proxy_url }}"

- name: no proxy for yum
  when: https_proxy_url is undefined and ansible_os_family == 'RedHat'
  lineinfile:
    dest: /etc/yum.conf
    state: absent
    regexp: '^proxy'

- name: Detect Travis
  when: lookup('env','TRAVIS')
  set_fact:
    travis: true

- name: Detect if EPEL is OK
  when: ansible_distribution == 'CentOS'
  set_fact:
    epel: ok

- name: Install EPEL repository
  when: ansible_os_family != 'Ubuntu' and epel is defined
  yum:
    name: epel-release
    state: present
    update_cache: yes
  tags:
    - server

- name: enable valid base urls
  when: https_proxy_url is defined and ansible_os_family == 'RedHat'
  shell: "sed -i 's/#baseurl/baseurl/g' /etc/yum.repos.d/*.repo"
  args:
    creates: /etc/yum.repos.d/epel.repo
