---
dependency:
  name: galaxy
driver:
  name: docker
lint: |
  set -e
  yamllint .
  ansible-lint
platforms:
  - name: base-epel-centos7
    image: centos:7
    privileged: true
provisioner:
  name: ansible
verifier:
  name: ansible
