---
# Standards: 0.2
dependency:
  name: galaxy
driver:
  name: docker
lint: |
  set -e
  yamllint .
  ansible-lint
platforms:
  - name: base-epel-ubi8
    image: registry.access.redhat.com/ubi8/ubi
    privileged: true
  - name: base-epel-centos7
    image: milcom/centos7-systemd
    privileged: true
  - name: base-epel-ubuntu
    image: ubuntu
    privileged: true
provisioner:
  name: ansible
verifier:
  name: ansible
