---
dependency:
  name: galaxy
driver:
  name: docker
lint:
  name: yamllint
platforms:
  - name: molecule_centos7
    image: centos:7
    privileged: True
provisioner:
  name: ansible
  config_options:
    defaults:
      remote_tmp: /tmp
  playbooks:
    create: create.yml
    converge: playbook.yml
    destroy: destroy.yml
  lint:
    name: ansible-lint
scenario:
  name: default
